import { Injectable } from "@angular/core";
import { BehaviorSubject } from "rxjs";
import { User } from "src/app/models/user.model";

@Injectable({
  providedIn: 'root'
})
export class StudentService {

  private _userList: User[] = [
    {
        id:"0",
        role:"proffesor",
        name:"Alumno",
        surname:"Apellido",
        birthdate:"11/01/2003",
        email:"a@a.com",
        gender:"masc",
        class:"1ºA"
    },
    {
        id:"1",
        role:"proffesor",
        name:"Alumno",
        surname:"Apellido",
        birthdate:"11/01/2003",
        email:"a@a.com",
        gender:"masc",
        class:"1ºA"
    },
    {
        id:"2",
        role:"proffesor",
        name:"Alumno",
        surname:"Apellido",
        birthdate:"11/01/2003",
        email:"a@a.com",
        gender:"masc",
        class:"1ºA"
    },
    {
        id:"3",
        role:"proffesor",
        name:"Alumno",
        surname:"Apellido",
        birthdate:"11/01/2003",
        email:"a@a.com",
        gender:"masc",
        class:"1ºA"
    },
    {
        id:"4",
        role:"proffesor",
        name:"Alumno",
        surname:"Apellido",
        birthdate:"11/01/2003",
        email:"a@a.com",
        gender:"masc",
        class:"1ºA"
    },
    {
        id:"5",
        role:"proffesor",
        name:"Alumno",
        surname:"Apellido",
        birthdate:"11/01/2003",
        email:"a@a.com",
        gender:"masc",
        class:"1ºA"
    },
    {
        id:"6",
        role:"proffesor",
        name:"Alumno",
        surname:"Apellido",
        birthdate:"11/01/2003",
        email:"a@a.com",
        gender:"masc",
        class:"1ºA"
    },
    {
        id:"7",
        role:"proffesor",
        name:"Alumno",
        surname:"Apellido",
        birthdate:"11/01/2003",
        email:"a@a.com",
        gender:"masc",
        class:"1ºA"
    },
    {
        id:"8",
        role:"proffesor",
        name:"Alumno",
        surname:"Apellido",
        birthdate:"11/01/2003",
        email:"a@a.com",
        gender:"masc",
        class:"1ºA"
    },
    {
        id:"9",
        role:"proffesor",
        name:"Alumno",
        surname:"Apellido",
        birthdate:"11/01/2003",
        email:"a@a.com",
        gender:"masc",
        class:"1ºA"
    },
    {
        id:"10",
        role:"proffesor",
        name:"Alumno",
        surname:"Apellido",
        birthdate:"11/01/2003",
        email:"a@a.com",
        gender:"masc",
        class:"1ºA"
    },
    {
        id:"11",
        role:"proffesor",
        name:"Alumno",
        surname:"Apellido",
        birthdate:"11/01/2003",
        email:"a@a.com",
        gender:"masc",
        class:"1ºA"
    },
    {
        id:"12",
        role:"proffesor",
        name:"Alumno",
        surname:"Apellido",
        birthdate:"11/01/2003",
        email:"a@a.com",
        gender:"masc",
        class:"1ºA"
    },
    {
        id:"13",
        role:"proffesor",
        name:"Alumno",
        surname:"Apellido",
        birthdate:"11/01/2003",
        email:"a@a.com",
        gender:"masc",
        class:"1ºA"
    },
    {
        id:"14",
        role:"proffesor",
        name:"Alumno",
        surname:"Apellido",
        birthdate:"11/01/2003",
        email:"a@a.com",
        gender:"masc",
        class:"1ºA"
    },
    {
        id:"15",
        role:"proffesor",
        name:"Alumno",
        surname:"Apellido",
        birthdate:"11/01/2003",
        email:"a@a.com",
        gender:"masc",
        class:"1ºA"
    },
    {
        id:"16",
        role:"proffesor",
        name:"Alumno",
        surname:"Apellido",
        birthdate:"11/01/2003",
        email:"a@a.com",
        gender:"masc",
        class:"1ºA"
    },
    {
        id:"17",
        role:"proffesor",
        name:"Alumno",
        surname:"Apellido",
        birthdate:"11/01/2003",
        email:"a@a.com",
        gender:"masc",
        class:"1ºA"
    },
    {
        id:"18",
        role:"proffesor",
        name:"Alumno",
        surname:"Apellido",
        birthdate:"11/01/2003",
        email:"a@a.com",
        gender:"masc",
        class:"1ºA"
    },
    {
        id:"19",
        role:"proffesor",
        name:"Alumno",
        surname:"Apellido",
        birthdate:"11/01/2003",
        email:"a@a.com",
        gender:"masc",
        class:"1ºA"
    }
  ]

  private _user:BehaviorSubject<User[]> = new BehaviorSubject(this._userList);
  public user$ = this._user.asObservable();

}