# -*- coding: utf-8 -*-
"""preguntas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nzyVw6w1hlgS5d3V8ogRQtDGYDsmzr-T
"""

#Materias
preguntas_materias = [
    '¿Cómo te sientes al enfrentarte a una asignatura o tema que te resulta particularmente difícil?',
    '¿Qué emociones experimentas al pensar en la ultilidad de algunas asignaturas de cara a tu carrera futura?',
    '¿Cómo te afecta emocionalmente el tiempo que le dedicas a tus materias?',
    '¿Qué sensaciones experimentas cuando consigues entender un concepto difícil en una de tus materias?',
    '¿Cómo te hace sentir el poder aplicar lo que has aprendido en una materia a situaciones de la vida real?',
    '¿Cómo te sientes cuando descubres que una materia te interesa más de lo que pensabas inicialmente?',
    '¿Cómo te sientes cuando recibes una calificación baja en una materia que te importa?',
    '¿Cómo te hace sentir el descubrir que una materia que pensabas que sería difícil resulta ser más fácil de lo esperado?',
    '¿Qué actividades o pasatiempos te ayudan a relajarte y cómo te hacen sentir fuera del entorno académico?',
    '¿Cómo te sientes al descubrir que disfrutas de una materia o área de estudio que no esperabas disfrutar tanto?'
    ]

# Compañeros
preguntas_companeros = [
    "¿Cómo te afecta emocionalmente el ambiente de tu clase con tus compañeros?",
    "¿Qué emociones experimentas al sentirte apoyado/a por tus compañeros de clase en tus estudios?",
    "¿Cómo te sientes al trabajar en equipo con tus compañeros de clase?",
    "¿Qué emociones experimentas al manejar las diferencias de opinión en los trabajos en grupo?",
    "¿Cómo te hizo sentir tu experiencia más reciente trabajando en un proyecto de grupo?",
    "¿Cómo te afecta emocionalmente tener más afinidad con algunos compañeros que con otros?",
    "¿Qué emociones experimentas al quedar con tus compañeros fuera del horario escolar?",
    "¿Cómo te sientes durante las excursiones?",
    "¿Qué papel juegan tus amigos en tu bienestar emocional durante el curso escolar?",
    "¿Cómo te sientes respecto a la interacción con tus compañeros de clase?",
    "¿Qué emociones experimentas al trabajar en proyectos o asignaciones grupales?",
    "¿Cómo te afecta positiva o negativamente la dinámica social en el aula?",
    "¿Qué emociones te provoca la colaboración con tus compañeros en actividades extracurriculares?",
    "¿Cómo te sientes respecto a la diversidad y la inclusión en tu grupo de compañeros?",
    "¿Qué emociones experimentas al hacer nuevos amigos en la escuela?",
    "¿Cómo te sientes respecto a la competencia académica con tus compañeros?",
    "¿Qué emociones te provoca la idea de hablar en público frente a tus compañeros?",
    "¿Cómo te afecta emocionalmente la relación con tus compañeros en situaciones de conflicto?",
    "¿Qué emociones experimentas al participar en eventos sociales escolares?"
    ]

#Profesores
preguntas_profesores = [
    '¿Cómo es tu comunicación emocional con tus profesores fuera del horario de clase?',
    '¿Cómo manejas a nivel emocional las críticas constructivas de tus profesores?',
    '¿Cómo te afecta emocionalmente recibir elogios de tus profesores?',
    '¿Cómo te sientes cuando hay un profesor con el que no conectas emocionalmente?',
    '¿Qué opinas a nivel personal de la metodología de enseñanza de tus profesores?',
    '¿Cómo percibes la relación emocional entre estudiantes y profesores en tu centro educativo?',
    'Si fueras profesor/a, ¿cómo gestionarías el aspecto emocional en tu clase?',
    '¿Cómo crees que podrían mejorar las relaciones emocionales entre profesores y estudiantes dentro del aula?'
]

#Centro educativo
preguntas_centro = [
    '¿Hay algo a nivel emocional que cambiarías en tu centro educativo?',
    '¿Cómo te afecta la temperatura del aula?',
    '¿Qué recursos y facilidades proporciona el centro educativo que consideras más útiles emocionalmente para tu aprendizaje?',
    '¿Sientes que el centro realmente te apoya emocionalmente en tus necesidades?',
    '¿Hay algún recurso o servicio que emocionalmente desearías que el centro educativo ofreciera para mejorar tu experiencia?',
    '¿Has tenido experiencias de mentoría que hayan sido especialmente valiosas a nivel emocional para tu desarrollo académico y personal?',
    '¿Cómo percibes emocionalmente los castigos en tu centro?'
]

#Estudios generales
estudios_generales = [
    "¿Cuáles son tus metas académicas a corto y largo plazo y cómo te afectan emocionalmente?",
    "¿Cómo manejas emocionalmente el estrés relacionado con los estudios?",
    "¿Has experimentado algún cambio importante en tu vida académica recientemente? ¿Cómo te ha afectado emocionalmente?",
    "¿Te han castigado alguna vez por sacar mala nota? ¿Cómo te afecta emocionalmente?",
    "¿Piensas que pasas mucho o poco tiempo en el centro y cómo te afecta emocionalmente?",
    "¿Cuál es tu motivación principal a nivel emocional para estudiar una variedad de materias en lugar de especializarte?",
    "¿Cuáles consideras que son las mayores recompensas emocionales de elegir estudios generales en lugar de una especialización temprana?",
    "¿Crees que la variedad de materias te ha ayudado a desarrollar una perspectiva más amplia y conectada emocionalmente del conocimiento?"
    ]

#Trabajos
preguntas_trabajos = [
    "¿Podrías compartir una experiencia significativa de uno de tus proyectos académicos? ¿Cuál fue tu papel y cómo te afectó a nivel emocional?",
    "¿Cómo influyó tu participación en proyectos académicos en tu conexión con tus compañeros de equipo? ¿Hubo momentos emocionales compartidos durante el proceso?",
    "¿Hubo momentos desafiantes en los que la colaboración en proyectos académicos puso a prueba tus emociones? ¿Cómo manejaste esas situaciones?",
    "¿Cómo crees que los proyectos han dejado una huella emocional en ti?",
    "Al enfrentarte a desafíos en tus trabajos académicos, ¿cómo has lidiado con las tensiones emocionales que puedan surgir?",
    "¿Hay algún proyecto del que te sientas particularmente orgulloso/a a nivel personal y emocional? ¿Por qué es tan significativo para ti?",
    "Cuando has aplicado tus conocimientos en situaciones prácticas fuera del aula, ¿cómo ha influido emocionalmente en tu percepción de la utilidad de tus estudios?"
    ]

#Personales
preguntas_personales = [
    "¿Cómo enfrentas y gestionas las tensiones personales durante esos momentos intensos de evaluaciones?",
    "¿Cómo afrontas las situaciones que despiertan en ti miedo o ansiedad, y qué aprendizajes obtienes de esas experiencias?",
    "En este momento, ¿cómo te describirías a ti mismo/a en términos emocionales y personales?",
    "¿Qué medidas tomas para cuidarte a nivel personal durante los períodos intensivos de estudio?",
    "¿Sientes una carga abrumadora al considerar tu futuro, o encuentras tranquilidad en el camino que estás construyendo?",
    "¿Ha cruzado por tu mente la idea de abandonar tus estudios en algún momento, y qué te ha llevado a reflexionar sobre eso?",
    "¿Cómo crees que tu experiencia en este centro educativo contribuye a la realización de tus metas a largo plazo?"
    ]

#Examenes
preguntas_examenes = [
    "¿Cómo te sientes después de terminar un examen que te ha salido bien?",
    "¿Cómo te sientes después de terminar un examen que te ha salido mal?",
    "¿Existe alguna preocupación específica que te embargue antes de enfrentar un examen y cómo lidiarías con ella?",
    "¿Encuentras algún aspecto del proceso de realizar exámenes particularmente desafiante o gratificante, y por qué?",
    "¿Crees que los exámenes son útiles como método de evaluación, o piensas que no son efectivos para medir tus conocimientos y habilidades?",
    "¿Te sienta bien sacar buena nota cuando el examen no te ha salido bien, o sigues pensando que podría ser mejor?"
    ]